### ISSUE TITLE
connect.cyb redesign

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#107]
ETH:

wallet settings
connection settings

**Comment by asadovka** [comment]
2 directions are here:

1. separate wallet & providers logic
![2018-12-20_14-37-42](https://user-images.githubusercontent.com/17406355/50282746-d6e3ba00-0464-11e9-959d-24548b993ccb.png)

2. Combine all blockchain data: blockchain settings (wallet, providers, key management)
![2018-12-20_14-39-22](https://user-images.githubusercontent.com/17406355/50282815-0bf00c80-0465-11e9-84ca-2dae5cc46955.png)

**Comment by mastercyb** [comment]
Would love to give some feedback :-)

**Comment by asadovka** [comment]
@xhipster you are welcome :)

**Comment by asadovka** [comment]
I will try to implement this mockup in storybook

**Comment by asadovka** [comment]
as we've decided to move all provider settings to separate apps there will be no separate connect.cyb.
eth.cyb, ipfs.cyb, cyb.cyb will be instead

**Comment by asadovka** [comment]
one page with 3 tabs
![ipfs](https://user-images.githubusercontent.com/17406355/52618612-e82fcc80-2ed1-11e9-8caf-cc0cc90be9b4.png)
![eth](https://user-images.githubusercontent.com/17406355/52618637-f7167f00-2ed1-11e9-8e01-8de4be6d70be.png)
![cyberd](https://user-images.githubusercontent.com/17406355/52618649-fe3d8d00-2ed1-11e9-9bdd-74787823ca8a.png)

**Comment by asadovka** [comment]
![2019-02-24_12-17-32](https://user-images.githubusercontent.com/17406355/53295448-3cba3c80-382e-11e9-8e46-8cb84e93893f.png)
![2019-02-24_12-17-41](https://user-images.githubusercontent.com/17406355/53295453-42178700-382e-11e9-99b7-13cd659b443d.png)
![2019-02-24_12-17-58](https://user-images.githubusercontent.com/17406355/53295455-4774d180-382e-11e9-9d27-6942f152913f.png)
![2019-02-24_12-18-12](https://user-images.githubusercontent.com/17406355/53295469-4ba0ef00-382e-11e9-84e4-89d420bef6b0.png)

**Comment by mastercyb** [comment]
It is completely great!
