### ISSUE TITLE
Release notes for 0.1

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#109]

**Comment by asadovka** [comment]
# 0.1.0 Euler

## Shell

### 1. Main page
- links on popular apps: chaingear, dragonereum, ipfs WebUI

### 2. Navigation bar
- back navigation (infitite steps)
- DURA support
- bookmarks button

### 3. ID bar
- notifications button
- settings button
- account info (balances of ETH & CYB, links on history, wallet & app bar)

### 4. App bar
- list of all cyb apps
- add/remove bookmark function

### 5. State bar
- IPFS/ETH/Cyber colored connection statuses
- popup windoe with detailed info

## Core Apps:

### 1. Multiblockchain Wallet:
- login & password functions
- ETH & CYB token support
- import addresses
- export private keys
- sending tokens

### 2. Chaingear - app for creation & management of registries, based on Ethereum
- separation of steps: registry initialization & schema definition
- registry & record management (fund, claim, transfer, delete)
- pause & resume registry
- beneficiaries panel
- permissions for records creation (only admin, all users)
- record fields validation (by unique)

### 3. Root Registry - registry for matching web3 content
- registry of apps (.help, .cyber, .wiki, .ewiki, .chaingear, .ipfsview, .dragons)

### 4. Cyber Search - app for searching in cyberd and linking results
- search in cyberd
- display of result's rank
- linking results

### 5. Web3 providers connection
- IPFS support (separate read & write)
- ETH support (mainet, kovan, rinkeby)
- Cyberd support (dev-euler testnet)

### 6. TXQ - transaction history of an account
- ETH & CYB transaction monitor
- Notifications for ETH & CYB pending transactions

### 7. History app - account's navigation history
- list of DURA links

### 8. Dragonereum - web3 game
- support of game
- internal notifications and views (ETH transactions)

### 9. Transaction signer
- custom transaction signer
- automatic gas price calculation

**Comment by asadovka** [comment]
@xhipster @Pechalka @vstavetski @Olga584 please, review and add info
