### ISSUE TITLE
Default plugins

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#11]
- pdf
- image
- video
- audio

**Comment by asadovka** [comment]
duplicate https://github.com/cybercongress/cyb/issues/11

**Comment by mastercyb** [comment]
Can somebody explain what is this feature about?

**Comment by asadovka** [comment]
@xhipster this feature is about showing file in IPFS instead of downloading it

done with https://github.com/cybercongress/cyb/issues/85

the pictures are showing. for video playing, we need to implement a streaming video player. same for the audio

**Comment by mastercyb** [comment]
I suppose we need to add two more issues, for video and audio.
