### ISSUE TITLE
Cyb linking do not work with euler testnet

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#116]
### Current Behavior

I successfully imported account, but is not able nor link nor see search results from remote node

### Definition of Done

Search and linking must work

**Comment by asadovka** [comment]
fixed.

possible solutions:

1. check access controls here:
![2019-01-09_20-16-43](https://user-images.githubusercontent.com/17406355/50916271-b7302800-144b-11e9-8a5f-ef9ab34f14eb.png)

2. check if ipfs hash of .cyber app is up to date

3. relaunch Cyb
