### ISSUE TITLE
Generate cyberd acc from existing ethereum one.

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyb-archeology#120]
### User Story
As a user, I want to use the same pub\priv key pair from Ethereum chain in cyberd chain. I don't know how it should be done exactly on UX side, but under the hood, it seems easy. Let's discuss possible ways to do it.

P.S. Currently, a user can copy private key from Ethereum wallet and restore cyberd account via that key. We need to make it smoother.

**Comment by asadovka** [comment]
@hleb-albau in the next release, we can generate cyberd accounts automatically when user imports or create ethereum account.

**Comment by mastercyb** [comment]
Completely agree. In reality an issue is a way more broader. Handling of keys, accounts and secrets in cyb currently unacceptable. We should fix it from top to bottom

**Comment by mastercyb** [comment]
Will be implemented as the part of https://github.com/cybercongress/cyb/issues/180
