### ISSUE TITLE
Send function doesn't work

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#123]
### Current Behavior
[comment]: # (Describe what actually happened.)

When I click on "send" button in ETH or CYB wallet I see white screen. Nothing happens. 

### Log
[comment]: # (Also you can attach log to this issue.)

Cyb version - Euler 0.1.0

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Working send function

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

![2019-01-11_10-59-47](https://user-images.githubusercontent.com/17406355/51020586-08e1cb00-1590-11e9-8042-2dda5a4fb5cd.png)

**Comment by hleb-albau** [comment]
see #124

**Comment by asadovka** [comment]
in build from dev branch send window opened, but nothing happens when I enter address & amount and press send

**Comment by asadovka** [comment]
in 0.1.1 release we will block send function

**Comment by asadovka** [comment]
@vstavetski please, add validation for cosmos address.
