### ISSUE TITLE
Update key docs

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#126]
Need to update all visionary docs:
1. Refresh cyb [whitepaper](https://github.com/cybercongress/cyb/blob/master/docs/cyb.md) for Euler release
2. Refresh dura.md
3. Add The Great Web definition

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/commit/6ffa3711803dfecb6a9ca948f3d13582e3682757

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/commit/7b782492c5b01b09d60f485bc36ee80f6e978fbd

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/commit/8d1889d1fe8b0ffadfffdc8964ec280c1b97241f

**Comment by mastercyb** [comment]
DURA specs is done. Cyb wp is a standalone task
