### ISSUE TITLE
Browsing modes

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#127]
Currently, we have no clear browser behavior, some actions are available for logined users, some are not.

As we've discussed in Cyb whitepaper, we should have 2 modes: anonymous, private.

In the current implementation, it can look like that:

1. Anonymous (by default). There are no users, ETH or Cybed adresses. Just .cyber app with a simple search function. No transaction or navigation history is saved in local storage (only for current session).

2. Private (after creation of user or login) - Default ETH or Cyberd accounts are generated, user can enjoy all functions of Cyb - linking results, transactions in apps and etc. user data belongs only to him.

@xhipster @Pechalka let's discuss it

**Comment by mastercyb** [comment]
I would argue that in anonymous mode (without id with broadband) the user must not have the ability to use .cyber

**Comment by asadovka** [comment]
@xhipster  I wrote that anon user could use .cyber) but can't link queries

**Comment by asadovka** [comment]
currently there will be no anonymous mode due to insecure IPFS connection. only logined users in private mode
