### ISSUE TITLE
Research for electron optimization

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#129]
In current build unarchived version of Cyb takes ~360 Mb of disk space. Quite a big part of size belongs to variety of drivers, libs and so on. Such artifacts are useless for us.

So the plan could be:

1. Analyze, what can we do with current electron implementation
2. research for alternative frameworks, such as [Tau](https://github.com/PhilippLgh/tau)

**Comment by cyborgshead** [comment]
I think we should try first build app with pruning @Pechalka @vstavetski

**Comment by mastercyb** [comment]
Not relevant anymore
