### ISSUE TITLE
hello.cyb design

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#13]
### Current Behavior

First thing I saw in Cyb was fucking long chunk of text that nobody will every read. It is not web3 is all about.

### Expected Behavior

> On first open of Cyb user have to feel like sparks shot out and cannons blared and the mountains crumbled and the seas roared.

### Solution

I hope we will able to do something prettier, more clear and shorter than MEW did (like explaining the whole shit about interface and private keys and all that stuff)

### Definition of Done

Users will remember how she first met Cyb.

She will forget her first computer, first kiss, first fuck, be she will always remember first time with Cyb

**Comment by asadovka** [comment]
Screens:

1. Hi! I'am Cyb a friendly robot, and I want to show you the new internet. But firstly let me help you to prepare for the adventure...

2. Wallet & accounts creation

3. Connection management

4. Some closing text...

**Comment by asadovka** [comment]
some ideas are [here](https://github.com/cybercongress/cyberdesign/tree/concept-cyb_13/cyb/browser/.exportedArtboards/Launch)

**Comment by asadovka** [comment]
browser logo will be animated

**Comment by asadovka** [comment]
add disclaimer

**Comment by asadovka** [comment]
![photo_2019-02-11_18-29-58](https://user-images.githubusercontent.com/17406355/52612372-f377fd80-2ebb-11e9-912a-bb194f5fb460.jpg)
