### ISSUE TITLE
Apply new .cyber

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#131]
We need to add the number of all validators, validators online.

Add ten last blocks, time, proposal.

**Comment by hleb-albau** [comment]
Database size is not relevant info, each client can use own data compaction algorithm. Links and cids count is enough as for me.

**Comment by asadovka** [comment]
@hleb-albau ok, what about validators?

**Comment by asadovka** [comment]
we've communicated with @hleb-albau. 

for validators we can make a table like this

![2019-01-28_13-03-59](https://user-images.githubusercontent.com/17406355/51817458-65b5e300-22fd-11e9-90b9-c956f5f51aef.png)

**Comment by asadovka** [comment]
@Pechalka let's analyze, what data we can get from our API for validators

**Comment by asadovka** [comment]
http://earth.cybernode.ai:34660/node_info


https://cosmos.network/rpc/#/

**Comment by asadovka** [comment]
Table:

1 tab - active validators
- validator's name (moniker)
- validator's address
- voting power
- bond height

**Comment by asadovka** [comment]
2 tab jailed

* validator's name (moniker)
* validator's address
* voting power
* bond height

**Comment by asadovka** [comment]
For Active and Jailed tabs table has the same coloumns 

![2019-02-05_19-37-55](https://user-images.githubusercontent.com/17406355/52276565-20d91e80-2985-11e9-9d60-91fc4f796f26.png)

**Comment by asadovka** [comment]
- .cyber - bandwidth, account stats, chain stats
- .cyber/wallet - address, fee, amount
- .cyber/validators - validators table & stats
- .cyber/blocks - blocks data
- .cyber/lottery - genesis addresses

**Comment by asadovka** [comment]
https://github.com/cybercongress/cyb/issues/215
