### ISSUE TITLE
Releasing without fixing github vulnerability alerts is not cool

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#132]
<img width="1039" alt="screenshot 2019-01-21 at 12 05 32" src="https://user-images.githubusercontent.com/410789/51467299-e7919380-1d74-11e9-9157-8f29969cf2f9.png">

**Comment by mastercyb** [comment]
Just wanted to point that these vulnerabilities affect crypto implementations sometime.

**Comment by asadovka** [comment]
@xhipster @vstavetski same is [here](https://github.com/cybercongress/chaingear)
