### ISSUE TITLE
Apply linking animation

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#139]
Inspired by @hleb-albau

Workflow:

1. A user opens search result page in .cyber app and wants to make a cyber.Link 
2. After successful entering of link parameters his answer lively moves up to search results
2. The answer has a timing status which shows a state of the link (processed, successful, failed)

**Comment by vbloher** [comment]
At the moment, after clicking on the "link" button, a message appears about the successful or failed link creation. If successful, the link is added to the end of the list of results with 'n/a' value of rank.

Next iteration will be complete after implementing of new UI.
