### ISSUE TITLE
Research for design system

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#140]
I think we've come to the moment when we need to use design systems.

I offer to use a working system out of the box and complete it step by step in the future.

Main criteria for the design system:

1. opensource system
2. Both react components and sketch file are needed
3. UI should be as close as possible to material UI
4. Better if there will be a grid system, layout structure in components
5. No inline CSS

A list of candidates:

1. https://evergreen.segment.com/
2. https://www.carbondesignsystem.com/
3. https://polaris.shopify.com/components/overlays/modal#navigation

Another solutions:

1. bootstrap material theme
2. https://github.com/jgthms/bulma

**Comment by Olga584** [comment]
https://design-system.pluralsight.com/components/actionmenu/

**Comment by asadovka** [comment]
@Olga584 nice, but I see it's more like a plugin, not complete sketch file. Also, something strange is with their releases on Github

**Comment by Olga584** [comment]
http://developer.royalcanin.com/ui_assets/elements/buttons.html

**Comment by Olga584** [comment]
https://mineral-ui.com/components/tabs

**Comment by asadovka** [comment]
@Olga584 seems that their work is in a big progress: https://mineral-ui.com/component-status

**Comment by Olga584** [comment]
https://v2.grommet.io/components

**Comment by Olga584** [comment]
https://polaris.shopify.com/components/overlays/modal#navigation

**Comment by Olga584** [comment]
https://ant.design/components/table/#header

**Comment by Olga584** [comment]
https://meetup.github.io/swarm-design-system/components

**Comment by asadovka** [comment]
@Olga584 ant design is rather cool for react components. but sketch file is on Chinese(

**Comment by asadovka** [comment]
I think the favorite, for now, is Carbon. This is how I see our design system can be - here are all animation rules, grids, layouts. We can develop step by step our own new product - cyberdesign, based on it!

**Comment by asadovka** [comment]
https://github.com/airbnb/react-sketchapp

**Comment by mastercyb** [comment]
Looks awesome

**Comment by asadovka** [comment]
@xhipster unfortunately, to use this thing you need to write custom components according to airbnb templates. our goal was to find out if this app could convert any react components.

**Comment by mastercyb** [comment]
Yesterday was the final round with @segment #evergreen, @jgthms #bulma and @semanticui. A lot of pros & cons. And the last argument is that the design system must be compact. Hence we decide to give a try to #evergreen.

![Screen Shot 2019-02-13 at 11.21.38.png](https://images.zenhubusercontent.com/54d82a3f7c6ccc6277a71d19/9d2a61e2-08ec-41bc-a940-b42e06e595f1)

The next step is to adapt it to our requirements

**Comment by mastercyb** [comment]
First impressions on the work with `evergreen` is very positive. I think it unlikely we will change I decision. Next step is reaching in development the point when we will be able to fork out evergreen to redesign its design a bit
