### ISSUE TITLE
Integration of IPFS node to CYB

### ISSUE THREAD

**Issue by cyborgshead** [cybercongress/cyb-archeology#159]
Back to later discussion about ipfs intergration in cyb. Browser, I think, should have build-in node and connected to it by default. This will open us a lot of points of features to implement and help grow of cyber's protocol

**Comment by asadovka** [comment]
Some questions to discuss:
1. bootstrap addresses
2. pin behavior
3.  node resources

**Comment by cyborgshead** [comment]
@asadovka 
as I understand ipfs node have prepared set of bootstrap nodes
what do you mean about pin behavior? where to put pinned files?

**Comment by asadovka** [comment]
@litvintech right, pin files locally for a while and address them to earth provider. or leave only locally. or make options for a user to choose.

seems that we can do different options depending on anonymous or not mode is

**Comment by cyborgshead** [comment]
@asadovka anonymous mode it’s not powerful disccussed yet, so the basic strategy and good start point it’s to pin files into electron app (electron-store for example) and address all of them

**Comment by mastercyb** [comment]
I think we should start to think on the storage permissions

**Comment by asadovka** [comment]
@litvintech problem also is in multithreading in electron we have 2 processes: main and render.

to run IPFS in separate process something like [this](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) can be used

**Comment by mastercyb** [comment]
Dublicate of https://github.com/cybercongress/cyb/issues/205
