### ISSUE TITLE
Research for IPFS integration types

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#166]
We need to find options of launching node. For example:

1. launch daemon in the system when the browser starts and kill it when browser quits. Then we need to attach IPFS build with browser release
2. Launch directly in browser

**Comment by cyborgshead** [comment]
I think that built-in browser node should start by default. Start and shutdown on browser launch and close. In advance provide experienced users option to connect to a local node, if this then saves params and on launch and closing connect to a local node.

**Comment by vbloher** [comment]
I tried to run in-process ipfs node [here](https://github.com/cybercongress/cyb/tree/166-ipfs-node-integration). It works for .cyber app (get CID from content, get content by CID), but we also need a ipfs gateway, for loading apps\pages. At the moment, there is a way to load pages using in-process ipfs node, but in this case you need to wait for the full content load.
So, additional research is needed here.

**Comment by asadovka** [comment]
current implementation: check if IPFS node is running on the device, if not - start own node on default port (or another free port)
