### ISSUE TITLE
Daemon for ETH->CYB's orders

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#176]
contract which takes ETH from user and gives him back CYB's from pool

**Comment by cyborgshead** [comment]
- [x] contract which takes ethers and emit event @litvintech 
- [x] daemon which looks for events from contract @litvintech 
- [x] transfer cyb's @litvintech 
@asadovka waiting for chain to be online to continue development of transfers

**Comment by asadovka** [comment]
@litvintech ok

**Comment by cyborgshead** [comment]
daemon ready, need the description of cyb's application @asadovka
