### ISSUE TITLE
Fix autodeploy for mac

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#18]
new version of cyb can not be opened on mac (security blocks launch)

**Comment by hleb-albau** [comment]
Can't do this on my Linux PC. Assigned @Pechalka as mac developer.

**Comment by asadovka** [comment]
duplicate https://github.com/cybercongress/cyb/issues/18

**Comment by asadovka** [comment]
done! https://github.com/cybercongress/cyb/commit/d04c2fbd5502dd4b6dc89570c6f37cf510a0bc27
