### ISSUE TITLE
cyb.ai store design

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#189]
- get browser -> starts of  latest cyb release downloading according to the operating system
- refresh landing content
- add a link to Github

**Comment by mastercyb** [comment]
@Olga584 today creates a concept of the store

**Comment by mastercyb** [comment]
First draft:

<img width="791" alt="screen shot 2019-02-26 at 13 55 13" src="https://user-images.githubusercontent.com/410789/53393191-47abd300-39ce-11e9-8b29-5ea657a907fb.png">
