### ISSUE TITLE
rr.cyb update 

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#19]
by default there is a RR from Chaingear, but user can create his own profiles for RR.

sources:

https://github.com/cybercongress/cyberdesign/tree/concept-cyb_19/cyb/apps/Root%20Registry

**Comment by asadovka** [comment]
1. First time on RR:

- can't make any changes, only create new RR
![root regisrty](https://user-images.githubusercontent.com/17406355/48206372-4ef79400-e37f-11e8-9c3d-f6dfba6ff77a.png)

2. Creation of custom RR:

![creation](https://user-images.githubusercontent.com/17406355/48206390-5dde4680-e37f-11e8-8bfb-7b38922603e0.png)

3. Custom registry from cyb template:

![template](https://user-images.githubusercontent.com/17406355/48206421-7189ad00-e37f-11e8-9401-11c50c5109be.png)

4. Custom empty registry:

![empty register](https://user-images.githubusercontent.com/17406355/48206446-80705f80-e37f-11e8-8c94-ba5e3c660e13.png)

5. Second time on cyb RR after creation custom RRs:

![menu](https://user-images.githubusercontent.com/17406355/48206481-954cf300-e37f-11e8-8df3-71dfe385e14e.png)

**Comment by asadovka** [comment]
I'll add screens with process of table editing later

**Comment by asadovka** [comment]
remarks from @Pechalka : 
- ability to create only one custom RR
- just make editable local version of cg's RR

**Comment by asadovka** [comment]
Updated version. Maybe there will be better add menu and custom RR by default. So user will need just to edit it without creation.

![root regisrty](https://user-images.githubusercontent.com/17406355/48552645-499fc980-e8ea-11e8-898e-0d45c44a8c81.png)

![custom](https://user-images.githubusercontent.com/17406355/48552641-499fc980-e8ea-11e8-8436-0ae8499be651.png)
![edit](https://user-images.githubusercontent.com/17406355/48552642-499fc980-e8ea-11e8-947f-5839d326a750.png)

![menu](https://user-images.githubusercontent.com/17406355/48552789-bfa43080-e8ea-11e8-8529-d79c689676e9.png)

**Comment by mastercyb** [comment]
Need more time to design the thing

**Comment by asadovka** [comment]
currently, there will be one rr.cyb:

- rr.cyb matches chaingear's rr
- rr.cyb can be reset (moved back to browser's version)
- rr.cyb can be updated (resynced with chaingear's rr)
- rr.cyb can be edited, but after reset or update data will be lost (to prevent lose of data export and import will be implemented)

**Comment by asadovka** [comment]
root will come from chaingear. we need just add a button to refresh data
