### ISSUE TITLE
Appstore UI

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#20]
Appstore gets data from Chaingear

There should be all apps, divided by groups (built-in and, all and users').

sources are here:

https://github.com/cybercongress/cyberdesign/tree/concept-cyb_20/cyb/apps/appstore/

**Comment by asadovka** [comment]
### Some ideas:

#### 1. Single page:
 
![image](https://user-images.githubusercontent.com/17406355/48073525-01005600-e1f0-11e8-8773-77e907a422e8.png)

![image](https://user-images.githubusercontent.com/17406355/48073544-08bffa80-e1f0-11e8-95e6-96b057e6c8f7.png)

    
#### 2. Multi-page:

![image](https://user-images.githubusercontent.com/17406355/48074366-d0b9b700-e1f1-11e8-957f-40b8cdb82264.png)


![image](https://user-images.githubusercontent.com/17406355/48074377-d7e0c500-e1f1-11e8-9745-ec0a9d318f6e.png)


![image](https://user-images.githubusercontent.com/17406355/48074390-dd3e0f80-e1f1-11e8-907c-c6c7039e6f5f.png)


![image](https://user-images.githubusercontent.com/17406355/48074398-e202c380-e1f1-11e8-9676-2e30ca3d4475.png)

**Comment by mastercyb** [comment]
Decide to postpone a task. Using Chaingear default registry now

**Comment by asadovka** [comment]
So, there will be no appstore as a standalone app now.

A user can type app.cyber and get top-ranked apps
