### ISSUE TITLE
Web3 blog of cybercongress

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#206]
I would love to read our blog in Cyb. We have content, but we don't have a process of publishing and makeup process

**Comment by SaveTheAles** [comment]
There are two key features to do:
- [ ] add automagic deploying blog in ipfs
- [ ] add rss 

The solution is create blog in our [wiki](https://wiki.cybercongress.ai/) as a separate tab 

For now all blog posts collecting from congress repo (congress/blog/releases) to library and deploying in web2 blog

Built and deployed in ipfs wiki displayed in Cyb correct
