### ISSUE TITLE
0.3 release video

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#230]
The result must include short product video and both cyb and cyber at work.

**Comment by mastercyb** [comment]
The decision is the following: Making a video based on [1984 Apple commercial](https://www.youtube.com/watch?v=axSnW-ygU5g). It starts as it is, but in the end the following message appears: 
```
On April 1
cyberCongress will introduce 
Cyb.
And you will see why 2019
won't be like "2019"
```

**Comment by mastercyb** [comment]
Not relevant anymore
