### ISSUE TITLE
API for DURA

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#231]
- Events for queries
- Subscriptions

**Comment by vbloher** [comment]
1. Implemented methods for access to application query:

- window.navi.getQuery() - returns current query from browser navigation bar (cyber•bar)
- window.navi.setQuery(string) - set new query to cyberbar
- window.navi.onQueryUpdate(callback) - subscribe to query change events

2. Unsubscribe from all webview listeners such as onNewBlock, onQueryUpdate, etc when we leave the application page (prevent memory leaks)

**Comment by mastercyb** [comment]
Let us think about naming a bit
