### ISSUE TITLE
Provide IPFS http client object to apps

### ISSUE THREAD

**Issue by vbloher** [cybercongress/cyb-archeology#239]
Provide IPFS http client object instead of ipfsConfig object to apps.
For example:
`window.ipfsClient`
This solution will help reduce the size of apps and simplify the development process.

**Comment by cyborgshead** [comment]
@vstavetski nice feature to try with, waiting for results with built-in node

**Comment by mastercyb** [comment]
The browser need complete architecture rethink. Closing this for the time being
