### ISSUE TITLE
Market vs BTC (future feature request)

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/cyb-archeology#252]
It would be cool to implement a market for trading BTC (and other coins) against CYB directly, as to not be dependent on centralised exchanges and solely on OTC trading. 

[An example can be seen here](https://market.merit.me/exchange), although a crappy project, but an interesting idea, that connects your light-wallet straight to an own "vendor", where orders can be matched one against the other.

Of course, it would require a proxy that is trusted, can such a proxy be the Aragon org? Or maybe anyone that stakes a certain amount of THC?

**Comment by mastercyb** [comment]
I think its more doable against ETH, than BTC. For BTC its better to add pl to bisq. But general problem remains the same. Arbitrage. To be honest I'd better wait for IBC, so CYB tokens could be tradable without any counterparty involvement.

I close this issue as it is more about cyberd when about browser
