### ISSUE TITLE
Built-in keystore

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#3]
I see some inconvenience for users if they will use the same keystore with parity-shell. Main reason is security. Lets start a discussion on how that is better to be done

**Comment by hleb-albau** [comment]
@asadovka move issue, please

**Comment by asadovka** [comment]
one seed phrase to rule 'em all

**Comment by mastercyb** [comment]
Duplicate of https://github.com/cybercongress/cyb/issues/150
