### ISSUE TITLE
ETH balance of active account is not updating in wallet.cyb

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#31]
### Current Behavior

Balance of active account is not updating

<img width="1045" alt="screenshot 2018-11-21 at 20 04 29" src="https://user-images.githubusercontent.com/410789/48860284-2a60da80-edc9-11e8-9931-e06b4a04d961.png">

### Reproduction

You need at least two ethereum account. Try to send from one to another.

**Comment by asadovka** [comment]
fixed in new version
