### ISSUE TITLE
Overall testing and critical bugfixing of Dragons

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#36]

**Comment by asadovka** [comment]
bugs:
-  after rejecting a transaction - app function freezes
- double scroll in app window
- sometimes pictures and animations are missed

**Comment by asadovka** [comment]
rejection bug is [fixed](https://github.com/cybercongress/cyb/commit/4a584ae1c566defb85fdaf38d5edafa7543b1265)
double scroll in not in priority now
missing pictures are caused by slow internet connection
