### ISSUE TITLE
Design history page

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#51]

**Comment by asadovka** [comment]
basic version:
![2018-12-03_17-51-12](https://user-images.githubusercontent.com/17406355/49381011-0afc7280-f724-11e8-8dea-650e70801d51.png)

**Comment by mastercyb** [comment]
Can we group by the app?

**Comment by asadovka** [comment]
yeah! we will come back to it after chaingear, signer and notifications implementation

**Comment by asadovka** [comment]
@xhipster something like this:

![2018-12-04_16-40-40](https://user-images.githubusercontent.com/17406355/49445616-617cb600-f7e3-11e8-9d31-15aa47407b57.png)

**Comment by asadovka** [comment]
there will be another issue for design update
