### ISSUE TITLE
Define better default favourites

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cyb-archeology#53]
Ideas that we can put best already working ipfs apps as preinstalled. Exampe is IPFS UI instead of Turkish wiki

**Comment by mastercyb** [comment]
@asadovka

**Comment by asadovka** [comment]
Wallet
Chaingear
Settings
Root Registry
Dragonereum
Help
Cyber Search
Wiki
History
Notifications
IPFS WebUI

**Comment by asadovka** [comment]
this is for release 0.1 now
