### ISSUE TITLE
Dragonereum mainnet testing

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyb-archeology#73]

**Comment by asadovka** [comment]
I've tried several types of mainnet connections:
- infura (basic and custom)
- earth
- local (parity 2.1.6)

Best solution for my Cyb was infura. Earth and parity gave unstable loading (Dragonereum frontend dropped very often)

**Comment by mastercyb** [comment]
It is now stable and sweet. Just turn off “use Dragonereum node” in ux. The deal was that the game didnt use local parity node at all.
